<atomic-term> ::= "(" <atomic-term> ")" | <type-term> | <object-term> | <relation-term>

<tuple-term> ::= "(" <tuple-term> ")" | <atomic-term> | <atomic-term> "," <tuple-term>

<term> ::= "(" <term> ")" | <tuple-term> | <qualified-term>

<qualified-term> ::= <object-term>::<type-term> | <term> ":" <statement> | <term> ":" <decapitated-relation>

<statement> ::= "{" <statement> "}" | <term-declaration> | <statement-declaration> | <predication-statement> | <relation-statement> | <argument> | <statement> "\and" <statement> 

<term-declaration> ::= "prim" "(" <tuple-term> ")" | "def" "{" <primary-predication-statement> "}" | "form" "(" <term> ")" | "form" "{" <term> "?=" <term> "}"

<statement-declaration> ::= "asrt" "{" <statement> "}" | "syn" "{" <statement> "}"

<primary-predication-statement> ::= <tuple-term> ";" <statment> | <tuple-term> ";" <decapitated-relation>

<predication-statement> ::= <term> ";" <statment> | <term> ";" <decapitated-relation>

<relation-statement> ::= <term> <relation-term> <term>

<decapitated-relation> ::= <relation-term> <term>

<argument> ::= "prv" "{" <statement> "|" <deduction> "}"

<deduction> ::= "{" <deduction> "}" | <premise> "\trfr" <conclusion>

<premise> ::= "{" <premise> "}" | <statement> | <deduction> | <premise> \and <premise>

<conclusion> ::= <statement> | <deduction> "\trfr" <conclusion> | "F"

<block-comment> ::= "/*" ("*"(^"/")|^"*")* "*/"

<line-comment> ::= "/#" (^"\n")* (^"\n" "\") "\n" 
