<term> ::= "(" <term> ")" | <type-term> | <object-term> | <qualified-term> | <relation-term> | <term> "," <term> 

<qualified-term> ::= "(" <object-term> <type-term> ")" | <term> ":" <statement> | <term> ":" "(" <statement> ")" | <term> ":" <decapitated-relation>

<statement> ::= "{" <statement> "}" | <term-declaration> | <statement-declaration> | <predication-statement> | <relation-statement> | <argument> | <statement> "\and" <statement>

<term-declaration> ::= "prim" "{" <term> "}" | "def" "{" <predication-statement> "}" | "form" "{" <term> "}" | "form" "{" <term> "?=" <term> "}"

<statement-declaration> ::= "let" "{" <statement> "}" | "syn" "{" <statement> "}"

<predication-statement> ::= <term> ";" <statment>

<relation-statement> ::= <term> <relation-term> <term>

<decapitated-relation> ::= <relation-term> <term>

<argument> ::= "prv" "{" <statement> "|" <deduction> "}"

<deduction> ::= "{" <deduction> "}" | <statement> "\trfr" <statement> | <statement> "\trfr" <deduction> | <deduction> "\trfr" "false"

<block-comment> ::= "/*" ("*"(^"/")|^"*")* "*/"

<line-comment> ::= "#" (^"\n")* "\n" 
