<term> ::= "(" <term> ")" | <type-term> | <object-term> | <qualified-term> | <relation-term>

<qualified-term> ::= <type-term> <object-term>| <term> ":" <statement> | <term> ":" <relation-term> <term>

<statement> ::= "{" <statement> "}" | <term-declaration> | <statement-declaration> | <predication-statement> | <relation-statement> | <argument> 

<term-declaration> ::= "prim" <term> | "def" <predication-statement> | "form" <term> |"form" <term> "?=" <term>

<statement-declaration> ::= "let" <statement> | "syn" <statement>

<predication-statement> ::= <term> ";" <statment>

<relation-statement> ::= <term> <relation-term> <term>

<argument> ::= "prv" <statement> "|" <deduction>

<deduction> ::= "{" <deduction> "}" <statement> "\trfr" <statement> | <statement> "\trfr" <deduction> | <deduction> "\trfr" "false"

<block-comment> ::= "/*" ("*"(^"/")|^"*")* "*/"

<line-comment> ::= "#" (^"\n")* "\n" 
